/*
 *  Copyright (c) 2019 Mastercard
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
    http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

 * 
 * Loyalty Airport Experience API
 * The Loyalty Airport Lounge APIs offers cardholders, via their issuers, the ability to  access the Mastercard Airport Lounge service through this digital channel.  Cardholders can search for airport lounges, get airport lounge details,  access airport lounges via their personalized Digital Membership Card,  and access their lounge history. These APIs can be used to build a rich,  interactive airport experience within the issuer's existing mobile application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: loyalty-benefits-support@mastercard.flowdock.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.example;

import java.util.ArrayList;
import java.util.List;

import com.mastercard.developer.interceptors.OkHttp2OAuth1Interceptor;
import com.mastercard.developer.loyalty_airport_client.ApiClient;
import com.mastercard.developer.loyalty_airport_client.ApiException;
import com.mastercard.developer.loyalty_airport_client.api.AirportApi;
import com.mastercard.developer.loyalty_airport_client.api.BundleProfileApi;
import com.mastercard.developer.loyalty_airport_client.model.Account;
import com.mastercard.developer.loyalty_airport_client.model.AccountExternal;
import com.mastercard.developer.loyalty_airport_client.model.Address;
import com.mastercard.developer.loyalty_airport_client.model.BundleUser;
import com.mastercard.developer.loyalty_airport_client.model.BundleUserData;
import com.mastercard.developer.loyalty_airport_client.model.BundleUserResponse;
import com.mastercard.developer.loyalty_airport_client.model.Email;
import com.mastercard.developer.loyalty_airport_client.model.LoungeAirport;
import com.mastercard.developer.loyalty_airport_client.model.LoungeDMC;
import com.mastercard.developer.loyalty_airport_client.model.LoungeDetail;
import com.mastercard.developer.loyalty_airport_client.model.LoungeEntitlement;
import com.mastercard.developer.loyalty_airport_client.model.LoungeHistoryItem;
import com.mastercard.developer.loyalty_airport_client.model.Name;
import com.mastercard.developer.loyalty_airport_client.model.User;
import com.mastercard.developer.loyalty_airport_client.model.UserProduct;

public class AirportApiDemo {
	
	 public static void main(String[] args) throws Exception {
		 
		 RequestHelper.loadProperties();
		 
		 ApiClient apiClient = new ApiClient();
		 apiClient.setBasePath(RequestHelper.getBaseURL());
		 apiClient.getHttpClient().interceptors().add(new OkHttp2OAuth1Interceptor(RequestHelper.getConsumerkey(),RequestHelper.getPrivateKey()));
		 apiClient.setDebugging(true);
	        
	     AirportApi airportApi = new AirportApi(apiClient);
	    
		if (runThisScenario(args, "registration")) {
			BundleProfileApi bundleProfileApi = new BundleProfileApi(apiClient);
			executeRegistrationScenario(bundleProfileApi);
		}

		if (runThisScenario(args, "lounges")) {
			executeLoungesScenario(airportApi);
		}

		if (runThisScenario(args, "loungeDetails")) {
			executeLoungeDetailsScenario(airportApi);
		}

		if (runThisScenario(args, "dmc")) {
			executeDMCScenario(airportApi);
		}

		if (runThisScenario(args, "entitlement")) {
			executeEntitlementsScenario(airportApi);
		}

		if (runThisScenario(args, "loungeHistory")) {
			executeHistoryScenario(airportApi);
		}

		if (runThisScenario(args, "error")) {
			executeErrorScenario(airportApi);
		}
	    }
	 
	 
	private static void executeRegistrationScenario(BundleProfileApi bundleProfileApi) {
		 BundleUser bundleUser = getRegistrationObject();
		 try {
			 printMessage("STARTING AIRPORT REGISTRATION FROM COMMAND LINE");
			 BundleUserResponse result = bundleProfileApi.createUser(bundleUser);
			 System.out.println("Parsed Response---------------");
			System.out.println(result);
			} catch (Exception e) {
				System.err.println("Exception when calling Registration");
				e.printStackTrace();
			}
	}

	private static void executeLoungesScenario(AirportApi airportApi) {
		String userId = "testRemediatedLDE0803";
		String panLastFourDigits = "0803";
		String searchText = "lon";
		String preferredLanguage = "en-GB";
		try {
			 printMessage("STARTING GET AIRPORT LOUNGES FROM COMMAND LINE");
			List<LoungeAirport> result = airportApi.loyaltyAirportLoungesGet(userId, panLastFourDigits, searchText,
					preferredLanguage);
			 System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling Lounges");
			e.printStackTrace();
		}
	}

	private static void executeLoungeDetailsScenario(AirportApi airportApi) {
		String loungeCode = "LHR13";
		String userId = "testRemediatedLDE0803";
		String panLastFourDigits = "0803";
		String preferredLanguage = "en-GB";
		try {
			printMessage("STARTING GET AIRPORT LOUNGE DETAILS FROM COMMAND LINE");
			LoungeDetail result = airportApi.loyaltyAirportLoungesLoungeCodeGet(loungeCode, userId, panLastFourDigits,
					preferredLanguage);
			 System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling Lounge Details");
			e.printStackTrace();
		}
	}

	private static void executeDMCScenario(AirportApi airportApi) {
		String userId = "testRemediatedLDE0803"; 
		String panLastFourDigits = "0803"; 
		try {
			printMessage("STARTING GET AIRPORT DMC FROM COMMAND LINE");
			LoungeDMC result = airportApi.loyaltyAirportDigitalMembershipCardsGet(userId, panLastFourDigits);
			 System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling Digital Membership card");
			e.printStackTrace();
		}
	}

	private static void executeEntitlementsScenario(AirportApi airportApi) {
		String userId = "testRemediatedLDE0803";
		String panLastFourDigits = "0803";
		try {
			printMessage("STARTING GET ENTITLEMENT FROM COMMAND LINE");
			List<LoungeEntitlement> result = airportApi.loyaltyAirportEntitlementsGet(userId, panLastFourDigits);
			 System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling entitlements");
			e.printStackTrace();
		}
	}

	private static void executeHistoryScenario(AirportApi airportApi) {
		String userId = "testRemediatedLDE0803";
		String panLastFourDigits = "0803";
		String preferredLanguage = "en-GB";
		try {
			printMessage("STARTING GET LOUNGE HISTORY FROM COMMAND LINE");
			List<LoungeHistoryItem> result = airportApi.loyaltyAirportVisitsGet(userId, panLastFourDigits,
					preferredLanguage, null, null);
			 System.out.println("Parsed Response---------------");
			System.out.println(result);
		} catch (Exception e) {
			System.err.println("Exception when calling lounge history");
			e.printStackTrace();
		}
	}
	
	private static void executeErrorScenario(AirportApi airportApi) {
		String userId = "0UcSwZBQX4";
		String panLastFourDigits = "UiCKNs6fr7NiD";
		String searchText = "NDzc7y";
		String preferredLanguage = "XNqfPv70B1f6";
		try {
			printMessage("STARTING GET AIRPORT LOUNGES ERROR SCENARIO FROM COMMAND LINE");
			airportApi.loyaltyAirportLoungesGet(userId, panLastFourDigits, searchText,
					preferredLanguage);
		} catch (ApiException e) {
			System.err.println("Exception when calling AirportApi Lounges");
		}
	}
	
	private static void printMessage(String scenario) {
		System.out.println("--------------------------------------------------------------------");
		System.out.println("--------------------------------------------------------------------");
		System.out.println(scenario+"---------------");
		System.out.println("--------------------------------------------------------------------");
		System.out.println("--------------------------------------------------------------------");
	}
	
	
	private static BundleUser getRegistrationObject() {
		BundleUser bundleUser = new BundleUser();
		BundleUserData bundleUserData = new BundleUserData();
		User user = new User();
		UserProduct userProduct = new UserProduct();
		Address address = new Address();
		Email email = new Email();
		Name name = new Name();
		List<Email> emails = new ArrayList<>();
		List<Address> addresses = new ArrayList<>();
		
		address.setCountry("BRA");
		address.setLocality("Guarulhos");
		address.setPostalCode("07272060");
		address.setRegion("SP");
		address.setStreetAddress("Rua Francisco");
	
		addresses.add(address);
		user.setAddresses(addresses);
		
		email.setValue("john5105@gmail.com");
		emails.add(email);
		user.setEmails(emails);

		name.setFamilyName("Smitherines");
		name.setGivenName("Johnathon");
		user.setName(name);
		
		user.setPreferredLanguage("en-US");
		user.setUserId("user5105");
		
		Account account=new Account();
       
        account.setCardExpiryDate("02/2022");
        account.setCvcCode("876");
       
        account.setNameOnCard("John Q Smith");
        account.setPan("1234xxxxxxxx5678");
       
        AccountExternal accountExternal = new AccountExternal();
        accountExternal.setIca(1017L);
        account.setObject(accountExternal);
        
        List<Account> accounts=new ArrayList<>();
        accounts.add(account);
      
        userProduct.setProduct("airport"); 
        userProduct.setAccounts(accounts);
      
        List<UserProduct> products = new ArrayList<>();
        products.add(userProduct);

        bundleUserData.setProducts(products);
        bundleUserData.setUser(user);
        bundleUser.setData(bundleUserData);
		
        return bundleUser;
		
	}
	
	private static boolean runThisScenario(String[] args, String scenario) {
		return (args!=null && args.length>0 && args[0].contains(scenario)) || (args == null || args.length == 0);
	}


}
